#!/usr/bin/env bash
set -euo pipefail

# ==========================================================
# Masoud WireGuard Manager (v2)
# Ubuntu 22.04
#
# Key fixes compared to v1:
#  - Safe args in remote bootstrap (${9:-}, ${10:-})
#  - Correct remote config: Endpoint=IRAN_PUBLIC_IP:PORT (not IP/CIDR fields)
#  - Handles "wg0 already exists" by auto cleanup before start
#  - Role-based flow: IRAN (recommended, does remote bootstrap) / KHAREJ (local setup/repair)
#  - Full Service Manager
#  - Optional Change Port helper
# ==========================================================

RED=$'\033[0;31m'
GRN=$'\033[0;32m'
YLW=$'\033[1;33m'
CYN=$'\033[0;36m'
NC=$'\033[0m'

BASE="/etc/masoud-wg"
KEYDIR="$BASE/keys"
CONFDIR="$BASE/conf"
WGDIR="/etc/wireguard"

require_root(){ [[ $EUID -eq 0 ]] || { echo "${RED}Run as root (sudo).${NC}"; exit 1; }; }
have(){ command -v "$1" >/dev/null 2>&1; }

prompt() {
  local __var="$1" __text="$2" __default="${3:-}"
  local __val=""
  if [[ -n "$__default" ]]; then
    read -r -p "$__text [$__default]: " __val
    __val="${__val:-$__default}"
  else
    read -r -p "$__text: " __val
  fi
  printf -v "$__var" "%s" "$__val"
}

yesno() {
  local __var="$1" __text="$2" __default="${3:-y}"
  local __ans=""
  read -r -p "$__text (y/n) [$__default]: " __ans
  __ans="${__ans:-$__default}"
  __ans="$(echo "$__ans" | tr '[:upper:]' '[:lower:]')"
  if [[ "$__ans" == "y" || "$__ans" == "yes" ]]; then
    printf -v "$__var" "yes"
  else
    printf -v "$__var" "no"
  fi
}

install_deps() {
  echo "${CYN}Installing dependencies...${NC}"
  apt-get update -y
  apt-get install -y wireguard iproute2 curl openssh-client iptables || true
  mkdir -p "$BASE" "$KEYDIR" "$CONFDIR" "$WGDIR"
  chmod 700 "$BASE" "$KEYDIR" "$CONFDIR"
}

gen_keys() {
  local name="$1"
  local priv="$KEYDIR/${name}.key"
  local pub="$KEYDIR/${name}.pub"
  if [[ -f "$priv" && -f "$pub" ]]; then
    return 0
  fi
  echo "${CYN}Generating WireGuard keys: ${name}${NC}"
  umask 077
  wg genkey | tee "$priv" | wg pubkey > "$pub"
  chmod 600 "$priv"
  chmod 644 "$pub"
}

read_file_trim() {
  local f="$1"
  [[ -f "$f" ]] || { echo "${RED}Missing file: $f${NC}"; exit 1; }
  tr -d '\r\n' < "$f"
}

cleanup_iface() {
  local iface="$1"
  # Avoid "wg0 already exists"
  if ip link show "$iface" >/dev/null 2>&1; then
    wg-quick down "$iface" >/dev/null 2>&1 || true
    ip link del "$iface" >/dev/null 2>&1 || true
  fi
}

enable_forwarding_local() {
  sysctl -w net.ipv4.ip_forward=1 >/dev/null
  sed -i '/^net\.ipv4\.ip_forward\s*=/d' /etc/sysctl.conf 2>/dev/null || true
  echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
}

write_conf_local() {
  local iface="$1" address="$2" listen_port="$3" privkey="$4"
  local peer_pub="$5" peer_endpoint="$6" peer_allowed="$7" keepalive="$8"

  local conf="$WGDIR/${iface}.conf"
  umask 077
  cat > "$conf" <<EOF
# Generated by masoud-wg-manager
[Interface]
Address = ${address}
ListenPort = ${listen_port}
PrivateKey = ${privkey}

[Peer]
PublicKey = ${peer_pub}
AllowedIPs = ${peer_allowed}
Endpoint = ${peer_endpoint}
PersistentKeepalive = ${keepalive}
EOF
  chmod 600 "$conf"
  echo "${GRN}Wrote:${NC} $conf"
}

remote_bootstrap() {
  # Run on IRAN, config remote (KHAREJ) via SSH
  local rhost="$1" ruser="$2" rport="$3" rkey="$4"
  local iface="$5"
  local r_address="$6" r_listen_port="$7" r_priv="$8"
  local peer_pub="$9" peer_allowed="${10}" peer_endpoint="${11}" keepalive="${12}"
  local do_nat="${13:-no}" ext_if="${14:-}"

  echo "${CYN}Remote bootstrap on ${ruser}@${rhost}:${rport}${NC}"

  ssh -i "$rkey" -p "$rport" -o StrictHostKeyChecking=no "$ruser@$rhost" bash -s -- \
    "$iface" "$r_address" "$r_listen_port" "$r_priv" "$peer_pub" "$peer_allowed" "$peer_endpoint" "$keepalive" "$do_nat" "$ext_if" <<'EOS'
set -euo pipefail

IFACE="$1"
ADDR="$2"
PORT="$3"
PRIV="$4"
PEER_PUB="$5"
PEER_ALLOWED="$6"
PEER_ENDPOINT="$7"
KEEPALIVE="$8"
DO_NAT="${9:-no}"
EXT_IF="${10:-}"

apt-get update -y
apt-get install -y wireguard iproute2 iptables || true

mkdir -p /etc/wireguard
chmod 700 /etc/wireguard

# Cleanup interface if exists
if ip link show "$IFACE" >/dev/null 2>&1; then
  wg-quick down "$IFACE" >/dev/null 2>&1 || true
  ip link del "$IFACE" >/dev/null 2>&1 || true
fi

CONF="/etc/wireguard/${IFACE}.conf"
umask 077
cat > "$CONF" <<EOF
# Generated by masoud-wg-manager (remote)
[Interface]
Address = ${ADDR}
ListenPort = ${PORT}
PrivateKey = ${PRIV}
EOF

# Optional NAT on remote for egress (if desired)
if [[ "$DO_NAT" == "yes" && -n "$EXT_IF" ]]; then
  sysctl -w net.ipv4.ip_forward=1 >/dev/null
  sed -i '/^net\.ipv4\.ip_forward\s*=/d' /etc/sysctl.conf 2>/dev/null || true
  echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

  cat >> "$CONF" <<EOF
PostUp = iptables -t nat -A POSTROUTING -o ${EXT_IF} -j MASQUERADE; iptables -A FORWARD -i ${IFACE} -j ACCEPT; iptables -A FORWARD -o ${IFACE} -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o ${EXT_IF} -j MASQUERADE; iptables -D FORWARD -i ${IFACE} -j ACCEPT; iptables -D FORWARD -o ${IFACE} -j ACCEPT
EOF
fi

cat >> "$CONF" <<EOF

[Peer]
PublicKey = ${PEER_PUB}
AllowedIPs = ${PEER_ALLOWED}
Endpoint = ${PEER_ENDPOINT}
PersistentKeepalive = ${KEEPALIVE}
EOF

chmod 600 "$CONF"

systemctl enable --now "wg-quick@${IFACE}.service" || true
systemctl restart "wg-quick@${IFACE}.service"
systemctl status "wg-quick@${IFACE}.service" --no-pager -l || true
EOS

  echo "${GRN}Remote bootstrap done.${NC}"
}

svc_list() {
  systemctl list-unit-files --type=service | awk '{print $1}' | grep -E '^wg-quick@.*\.service$' || true
}

select_service() {
  local services; mapfile -t services < <(svc_list)
  if [[ ${#services[@]} -eq 0 ]]; then
    echo "${YLW}No wg-quick services found.${NC}"
    return 1
  fi
  echo
  echo "${CYN}Select a service:${NC}"
  local i=1
  for s in "${services[@]}"; do echo "  [$i] $s"; ((i++)); done
  echo "  [0] Cancel"
  read -r -p "Choice: " idx
  [[ "${idx:-}" =~ ^[0-9]+$ ]] || return 1
  [[ "$idx" -eq 0 ]] && return 1
  (( idx>=1 && idx<=${#services[@]} )) || return 1
  SELECTED="${services[$((idx-1))]}"
  return 0
}

service_manager() {
  while true; do
    echo
    echo "------------------------------"
    echo " Service Manager (WireGuard)"
    echo "------------------------------"
    echo "1) List services"
    echo "2) Start"
    echo "3) Stop"
    echo "4) Restart"
    echo "5) Status"
    echo "6) Logs"
    echo "7) Remove (select iface: stop + delete conf)"
    echo "0) Back"
    read -r -p "Select: " ch
    case "${ch:-}" in
      1) svc_list | sed 's/^/ - /' ;;
      2) select_service && systemctl start "$SELECTED" ;;
      3) select_service && systemctl stop "$SELECTED" ;;
      4) select_service && systemctl restart "$SELECTED" ;;
      5) select_service && systemctl status "$SELECTED" --no-pager -l ;;
      6) select_service && journalctl -u "$SELECTED" -n 200 --no-pager ;;
      7)
        prompt IFACE "Interface to remove" "wg0"
        systemctl disable --now "wg-quick@${IFACE}.service" 2>/dev/null || true
        cleanup_iface "$IFACE"
        rm -f "/etc/wireguard/${IFACE}.conf"
        echo "${YLW}Removed ${IFACE}.${NC}"
        ;;
      0) break ;;
      *) echo "${RED}Invalid.${NC}" ;;
    esac
  done
}

wg_status() {
  echo "${CYN}wg show:${NC}"
  wg show || true
  echo
  prompt IFACE "Show interface status for" "wg0"
  ip addr show "$IFACE" 2>/dev/null || echo "No such iface: $IFACE"
}

change_port_helper() {
  prompt IFACE "Interface to change port" "wg0"
  prompt NEWPORT "New UDP port" "443"
  local conf="/etc/wireguard/${IFACE}.conf"
  [[ -f "$conf" ]] || { echo "${RED}Missing conf: $conf${NC}"; return; }

  # Change ListenPort
  sed -i -E "s/^ListenPort\s*=\s*[0-9]+/ListenPort = ${NEWPORT}/" "$conf"

  # Change Endpoint port (best-effort) for the peer line
  # If endpoint exists: x.x.x.x:old -> x.x.x.x:new
  sed -i -E "s/^(Endpoint\s*=\s*[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+):[0-9]+/\1:${NEWPORT}/" "$conf"

  echo "${GRN}Updated:${NC} $conf"
  cleanup_iface "$IFACE"
  systemctl restart "wg-quick@${IFACE}.service" || true
  wg show "$IFACE" || true
}

menu() {
  cat <<'EOF'

==============================
 Masoud WireGuard Manager (v2)
==============================

1) Install dependencies
2) Setup as IRAN (recommended): create local wg + remote bootstrap via SSH
3) Setup as KHAREJ (local only / repair): write local wg0.conf using provided keys
4) Status (wg show / ip addr)
5) Service Manager (list/select/start/stop/restart/logs/remove)
6) Change Port helper (e.g. 443/udp test)
0) Exit
EOF
}

require_root

while true; do
  menu
  read -r -p "Select: " CH
  case "${CH:-}" in
    1)
      install_deps
      ;;

    2)
      install_deps

      prompt IFACE "Interface name" "wg0"

      # Remote SSH info (KHAREJ)
      prompt KHAREJ_HOST "Remote (KHAREJ) SSH host/IP" ""
      prompt KHAREJ_USER "Remote SSH user" "root"
      prompt KHAREJ_SSH_PORT "Remote SSH port" "22"
      prompt KHAREJ_SSH_KEY "SSH private key path (for remote login)" "/root/.ssh/id_ed25519"

      # Public IPs (IMPORTANT for correct endpoints)
      prompt IRAN_PUBLIC_IP "THIS server public IP (IRAN)" ""
      prompt KHAREJ_PUBLIC_IP "Remote server public IP (KHAREJ)" "$KHAREJ_HOST"

      # WG IPs
      prompt IRAN_WG_IP "THIS server WG IP" "10.66.0.1/32"
      prompt KHAREJ_WG_IP "REMOTE server WG IP" "10.66.0.2/32"

      # Ports
      prompt IRAN_PORT "THIS server ListenPort (UDP)" "51820"
      prompt KHAREJ_PORT "REMOTE server ListenPort (UDP)" "51820"
      prompt KEEPALIVE "PersistentKeepalive" "25"

      prompt ROUTE_SUBNET "Optional subnet to route via WG (empty=none)" ""

      # Keys (stored on IRAN)
      gen_keys "iran-${IFACE}"
      gen_keys "kharej-${IFACE}"

      IR_PRIV="$(read_file_trim "$KEYDIR/iran-${IFACE}.key")"
      IR_PUB="$(read_file_trim "$KEYDIR/iran-${IFACE}.pub")"
      KH_PRIV="$(read_file_trim "$KEYDIR/kharej-${IFACE}.key")"
      KH_PUB="$(read_file_trim "$KEYDIR/kharej-${IFACE}.pub")"

      # AllowedIPs minimal p2p
      IR_ALLOWED="$KHAREJ_WG_IP"
      KH_ALLOWED="$IRAN_WG_IP"
      if [[ -n "$ROUTE_SUBNET" ]]; then
        IR_ALLOWED="${KHAREJ_WG_IP},${ROUTE_SUBNET}"
      fi

      # Endpoints
      # On IRAN: peer endpoint is KHAREJ_PUBLIC_IP:KHAREJ_PORT
      IR_PEER_ENDPOINT="${KHAREJ_PUBLIC_IP}:${KHAREJ_PORT}"
      # On KHAREJ: peer endpoint is IRAN_PUBLIC_IP:IRAN_PORT
      KH_PEER_ENDPOINT="${IRAN_PUBLIC_IP}:${IRAN_PORT}"

      # Local forwarding?
      yesno DO_FWD "Enable IPv4 forwarding on THIS server?" "n"
      [[ "$DO_FWD" == "yes" ]] && enable_forwarding_local

      # Write local conf (IRAN)
      cleanup_iface "$IFACE"
      write_conf_local "$IFACE" "$IRAN_WG_IP" "$IRAN_PORT" "$IR_PRIV" \
        "$KH_PUB" "$IR_PEER_ENDPOINT" "$IR_ALLOWED" "$KEEPALIVE"

      # Remote NAT?
      yesno DO_NAT "On remote (KHAREJ), enable forwarding+NAT (MASQUERADE)?" "n"
      EXT_IF=""
      if [[ "$DO_NAT" == "yes" ]]; then
        prompt EXT_IF "Remote outbound interface (e.g. eth0)" "eth0"
      fi

      # Remote bootstrap (KHAREJ)
      remote_bootstrap \
        "$KHAREJ_HOST" "$KHAREJ_USER" "$KHAREJ_SSH_PORT" "$KHAREJ_SSH_KEY" \
        "$IFACE" "$KHAREJ_WG_IP" "$KHAREJ_PORT" "$KH_PRIV" \
        "$IR_PUB" "$KH_ALLOWED" "$KH_PEER_ENDPOINT" "$KEEPALIVE" \
        "$DO_NAT" "$EXT_IF"

      # Start local service
      systemctl enable --now "wg-quick@${IFACE}.service" || true
      systemctl restart "wg-quick@${IFACE}.service"
      echo "${GRN}Local WireGuard started.${NC}"

      wg show "$IFACE" || true
      ;;

    3)
      install_deps
      prompt IFACE "Interface name" "wg0"

      # KHAREJ local/repair mode (no SSH)
      prompt KHAREJ_WG_IP "THIS server WG IP (KHAREJ)" "10.66.0.2/32"
      prompt KHAREJ_PORT "THIS server ListenPort (UDP)" "51820"
      prompt IRAN_PUBLIC_IP "IRAN public IP (peer endpoint)" ""
      prompt IRAN_PORT "IRAN ListenPort (UDP)" "51820"
      prompt IRAN_PUBKEY "IRAN public key" ""
      prompt KHAREJ_PRIVKEY "THIS server private key (KHAREJ)" ""
      prompt KEEPALIVE "PersistentKeepalive" "25"

      cleanup_iface "$IFACE"
      write_conf_local "$IFACE" "$KHAREJ_WG_IP" "$KHAREJ_PORT" "$KHAREJ_PRIVKEY" \
        "$IRAN_PUBKEY" "${IRAN_PUBLIC_IP}:${IRAN_PORT}" "10.66.0.1/32" "$KEEPALIVE"

      systemctl enable --now "wg-quick@${IFACE}.service" || true
      systemctl restart "wg-quick@${IFACE}.service"
      systemctl status "wg-quick@${IFACE}.service" --no-pager -l || true
      ;;

    4)
      wg_status
      ;;

    5)
      service_manager
      ;;

    6)
      change_port_helper
      ;;

    0) exit 0 ;;
    *) echo "${RED}Invalid.${NC}" ;;
  esac
done
