#!/usr/bin/env bash
set -euo pipefail

# ==========================================================
# Masoud WireGuard Manager (v1.0)
# Ubuntu 22.04
# Site-to-Site WireGuard tunnel (IRAN <-> KHAREJ)
#
# Features:
#  - Install deps (wireguard, iproute2, ufw optional)
#  - Generate keys (stored under /etc/masoud-wg/keys)
#  - Create wg0 config on THIS server
#  - Remote bootstrap (over SSH): create wg0 on remote + enable service
#  - Optional: enable IP forwarding + NAT on remote (if you want egress)
#  - Service Manager (list/select/start/stop/restart/status/logs/remove)
#
# Defaults:
#  - IFACE: wg0
#  - IRAN_IP: 10.66.0.1/32
#  - KHAREJ_IP: 10.66.0.2/32
# ==========================================================

RED=$'\033[0;31m'
GRN=$'\033[0;32m'
YLW=$'\033[1;33m'
CYN=$'\033[0;36m'
NC=$'\033[0m'

BASE="/etc/masoud-wg"
KEYDIR="$BASE/keys"
CONFDIR="$BASE/conf"
UNITDIR="/etc/systemd/system"
WG_DIR="/etc/wireguard"

require_root(){ [[ $EUID -eq 0 ]] || { echo "${RED}Run as root (sudo).${NC}"; exit 1; }; }
have(){ command -v "$1" >/dev/null 2>&1; }

prompt() {
  local __var="$1" __text="$2" __default="${3:-}"
  local __val=""
  if [[ -n "$__default" ]]; then
    read -r -p "$__text [$__default]: " __val
    __val="${__val:-$__default}"
  else
    read -r -p "$__text: " __val
  fi
  printf -v "$__var" "%s" "$__val"
}

yesno() {
  local __var="$1" __text="$2" __default="${3:-y}"
  local __ans=""
  read -r -p "$__text (y/n) [$__default]: " __ans
  __ans="${__ans:-$__default}"
  __ans="$(echo "$__ans" | tr '[:upper:]' '[:lower:]')"
  if [[ "$__ans" == "y" || "$__ans" == "yes" ]]; then
    printf -v "$__var" "yes"
  else
    printf -v "$__var" "no"
  fi
}

install_deps() {
  echo "${CYN}Installing dependencies...${NC}"
  apt-get update -y
  apt-get install -y wireguard iproute2 curl openssh-client
  mkdir -p "$BASE" "$KEYDIR" "$CONFDIR" "$WG_DIR"
  chmod 700 "$BASE" "$KEYDIR" "$CONFDIR"
}

gen_keys() {
  local name="$1"
  local priv="$KEYDIR/${name}.key"
  local pub="$KEYDIR/${name}.pub"
  if [[ -f "$priv" && -f "$pub" ]]; then
    return 0
  fi
  echo "${CYN}Generating WireGuard keys: ${name}${NC}"
  umask 077
  wg genkey | tee "$priv" | wg pubkey > "$pub"
  chmod 600 "$priv"
  chmod 644 "$pub"
}

read_key() {
  local f="$1"
  [[ -f "$f" ]] || { echo "${RED}Missing key file: $f${NC}"; exit 1; }
  tr -d '\n' < "$f"
}

enable_ip_forwarding() {
  # safe idempotent
  sysctl -w net.ipv4.ip_forward=1 >/dev/null
  if ! grep -q '^net.ipv4.ip_forward=1' /etc/sysctl.conf 2>/dev/null; then
    # remove existing line if present, then append
    sed -i '/^net\.ipv4\.ip_forward\s*=/d' /etc/sysctl.conf 2>/dev/null || true
    echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
  fi
}

write_wg_conf() {
  local iface="$1" address="$2" listen_port="$3" privkey="$4"
  local peer_pub="$5" peer_endpoint="$6" peer_allowed="$7" keepalive="$8"

  local conf="$WG_DIR/${iface}.conf"
  umask 077
  cat > "$conf" <<EOF
# Generated by masoud-wg-manager
[Interface]
Address = ${address}
ListenPort = ${listen_port}
PrivateKey = ${privkey}

[Peer]
PublicKey = ${peer_pub}
AllowedIPs = ${peer_allowed}
Endpoint = ${peer_endpoint}
PersistentKeepalive = ${keepalive}
EOF

  chmod 600 "$conf"
  echo "${GRN}Wrote:${NC} $conf"
}

apply_nat_rules_remote_note() {
  cat <<'EOF'
NAT reminder:
- If you want traffic from IRAN to exit via KHAREJ, enable forwarding+NAT on KHAREJ.
- This script can do it during Remote Bootstrap (recommended = y).
EOF
}

remote_bootstrap() {
  local rhost="$1" ruser="$2" rport="$3" rkey="$4"
  local iface="$5"
  local r_address="$6" r_listen_port="$7" r_priv="$8"
  local l_pub="$9" l_endpoint="${10}" l_allowed="${11}" keepalive="${12}"
  local do_nat="${13}" ext_if="${14}"

  echo "${CYN}Remote bootstrap on ${ruser}@${rhost}:${rport}${NC}"

  # Install deps and write config on remote
  ssh -i "$rkey" -p "$rport" -o StrictHostKeyChecking=no "$ruser@$rhost" bash -s -- \
    "$iface" "$r_address" "$r_listen_port" "$r_priv" "$l_pub" "$l_allowed" "$l_endpoint" "$keepalive" "$do_nat" "$ext_if" <<'EOS'
set -euo pipefail
IFACE="$1"
ADDR="$2"
PORT="$3"
PRIV="$4"
PEER_PUB="$5"
PEER_ALLOWED="$6"
PEER_ENDPOINT="$7"
KEEPALIVE="$8"
DO_NAT="$9"
EXT_IF="${10}"

apt-get update -y
apt-get install -y wireguard iproute2

mkdir -p /etc/wireguard
chmod 700 /etc/wireguard

CONF="/etc/wireguard/${IFACE}.conf"
umask 077
cat > "$CONF" <<EOF
# Generated by masoud-wg-manager (remote)
[Interface]
Address = ${ADDR}
ListenPort = ${PORT}
PrivateKey = ${PRIV}
EOF

# Optional NAT + forwarding (only if requested)
if [[ "$DO_NAT" == "yes" ]]; then
  # Enable forwarding now + persist
  sysctl -w net.ipv4.ip_forward=1 >/dev/null
  sed -i '/^net\.ipv4\.ip_forward\s*=/d' /etc/sysctl.conf 2>/dev/null || true
  echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

  # Add PostUp/PostDown NAT if EXT_IF provided
  if [[ -n "$EXT_IF" ]]; then
    cat >> "$CONF" <<EOF
PostUp = iptables -t nat -A POSTROUTING -o ${EXT_IF} -j MASQUERADE; iptables -A FORWARD -i ${IFACE} -j ACCEPT; iptables -A FORWARD -o ${IFACE} -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o ${EXT_IF} -j MASQUERADE; iptables -D FORWARD -i ${IFACE} -j ACCEPT; iptables -D FORWARD -o ${IFACE} -j ACCEPT
EOF
  fi
fi

cat >> "$CONF" <<EOF

[Peer]
PublicKey = ${PEER_PUB}
AllowedIPs = ${PEER_ALLOWED}
Endpoint = ${PEER_ENDPOINT}
PersistentKeepalive = ${KEEPALIVE}
EOF

chmod 600 "$CONF"

systemctl enable --now "wg-quick@${IFACE}.service"
systemctl restart "wg-quick@${IFACE}.service"
systemctl status "wg-quick@${IFACE}.service" --no-pager || true
EOS

  echo "${GRN}Remote bootstrap done.${NC}"
}

svc_list() {
  systemctl list-unit-files --type=service | awk '{print $1}' | grep -E '^(wg-quick@.*|masoud-wg-.*)\.service$' || true
}

select_service() {
  local services; mapfile -t services < <(svc_list)
  if [[ ${#services[@]} -eq 0 ]]; then
    echo "${YLW}No wg/masoud services found.${NC}"
    return 1
  fi
  echo
  echo "${CYN}Select a service:${NC}"
  local i=1
  for s in "${services[@]}"; do echo "  [$i] $s"; ((i++)); done
  echo "  [0] Cancel"
  read -r -p "Choice: " idx
  [[ "${idx:-}" =~ ^[0-9]+$ ]] || return 1
  [[ "$idx" -eq 0 ]] && return 1
  (( idx>=1 && idx<=${#services[@]} )) || return 1
  SELECTED="${services[$((idx-1))]}"
  return 0
}

service_manager() {
  while true; do
    echo
    echo "------------------------------"
    echo " Service Manager (WG)"
    echo "------------------------------"
    echo "1) List services"
    echo "2) Start"
    echo "3) Stop"
    echo "4) Restart"
    echo "5) Status"
    echo "6) Logs"
    echo "7) Remove wg0 (local cleanup)"
    echo "0) Back"
    read -r -p "Select: " ch
    case "${ch:-}" in
      1) svc_list | sed 's/^/ - /' ;;
      2) select_service && systemctl start "$SELECTED" && echo "${GRN}Started${NC} $SELECTED" ;;
      3) select_service && systemctl stop "$SELECTED" && echo "${YLW}Stopped${NC} $SELECTED" ;;
      4) select_service && systemctl restart "$SELECTED" && echo "${GRN}Restarted${NC} $SELECTED" ;;
      5) select_service && systemctl status "$SELECTED" --no-pager ;;
      6) select_service && journalctl -u "$SELECTED" -n 200 --no-pager ;;
      7)
        yesno OK "Remove local wg0 (stop service + delete config)?" "n"
        if [[ "$OK" == "yes" ]]; then
          systemctl disable --now wg-quick@wg0.service 2>/dev/null || true
          rm -f /etc/wireguard/wg0.conf
          ip link del wg0 2>/dev/null || true
          echo "${YLW}Removed local wg0.${NC}"
        fi
        ;;
      0) break ;;
      *) echo "${RED}Invalid.${NC}" ;;
    esac
  done
}

wg_status_quick() {
  echo "${CYN}wg show:${NC}"
  wg show || true
  echo
  echo "${CYN}ip addr show wg0:${NC}"
  ip addr show wg0 2>/dev/null || echo "wg0 not found"
}

menu() {
  cat <<'EOF'

==============================
 Masoud WireGuard Manager
==============================

1) Install dependencies
2) Create WG site-to-site (THIS=IRAN, Remote=KHAREJ) + Remote Bootstrap
3) Remote Bootstrap only (configure KHAREJ via SSH)
4) Status (wg show)
5) Service Manager (list/select/start/stop/restart/logs/remove)
0) Exit
EOF
}

require_root

while true; do
  menu
  read -r -p "Select: " CH
  case "${CH:-}" in
    1)
      install_deps
      ;;
    2)
      install_deps

      IFACE="wg0"
      prompt IFACE "Interface name" "$IFACE"

      # Local/Remote basics
      prompt KHAREJ_HOST "Remote (KHAREJ) SSH host/IP" ""
      prompt KHAREJ_USER "Remote SSH user" "root"
      prompt KHAREJ_SSH_PORT "Remote SSH port" "22"
      prompt KHAREJ_SSH_KEY "SSH private key path (for remote login)" "/root/.ssh/id_ed25519"

      # WG ports & IPs
      prompt LOCAL_WG_IP "THIS server WG IP" "10.66.0.1/32"
      prompt REMOTE_WG_IP "REMOTE server WG IP" "10.66.0.2/32"
      prompt LOCAL_LISTEN "THIS server WG ListenPort (UDP)" "51820"
      prompt REMOTE_LISTEN "REMOTE server WG ListenPort (UDP)" "51820"
      prompt KEEPALIVE "PersistentKeepalive" "25"

      # Endpoint directions:
      # - On IRAN config, peer endpoint is KHAREJ public IP:REMOTE_LISTEN
      KH_ENDPOINT="${KHAREJ_HOST}:${REMOTE_LISTEN}"

      # AllowedIPs:
      # Minimal p2p:
      #  - On IRAN, allow remote wg IP /32
      #  - On KHAREJ, allow local wg IP /32
      L_ALLOWED="${REMOTE_WG_IP}"
      R_ALLOWED="${LOCAL_WG_IP}"

      # Optional: route subnet via WG (advanced)
      prompt ROUTE_SUBNET "Optional subnet to route via WG (empty=none)" ""
      if [[ -n "$ROUTE_SUBNET" ]]; then
        # If you route subnet, add it into remote allowed too
        L_ALLOWED="${REMOTE_WG_IP},${ROUTE_SUBNET}"
        # remote should allow local /32 plus maybe local subnet (not assumed)
      fi

      # Keys
      gen_keys "iran-${IFACE}"
      gen_keys "kharej-${IFACE}"

      IR_PRIV="$(read_key "$KEYDIR/iran-${IFACE}.key")"
      IR_PUB="$(read_key "$KEYDIR/iran-${IFACE}.pub")"
      KH_PRIV="$(read_key "$KEYDIR/kharej-${IFACE}.key")"
      KH_PUB="$(read_key "$KEYDIR/kharej-${IFACE}.pub")"

      # Enable forwarding locally? (only if routing/NAT needed)
      yesno DO_LOCAL_FWD "Enable IPv4 forwarding on THIS server?" "n"
      [[ "$DO_LOCAL_FWD" == "yes" ]] && enable_ip_forwarding

      # Write local wg conf
      write_wg_conf "$IFACE" "$LOCAL_WG_IP" "$LOCAL_LISTEN" "$IR_PRIV" "$KH_PUB" "$KH_ENDPOINT" "$L_ALLOWED" "$KEEPALIVE"

      # Remote NAT (only if you want IRAN traffic to egress via KHAREJ)
      yesno DO_NAT "On remote (KHAREJ), enable forwarding+NAT (MASQUERADE)?" "n"
      EXT_IF=""
      if [[ "$DO_NAT" == "yes" ]]; then
        prompt EXT_IF "Remote outbound interface (e.g. eth0)" "eth0"
      fi

      echo "${CYN}Bootstrapping remote WireGuard config...${NC}"
      remote_bootstrap \
        "$KHAREJ_HOST" "$KHAREJ_USER" "$KHAREJ_SSH_PORT" "$KHAREJ_SSH_KEY" \
        "$IFACE" "$REMOTE_WG_IP" "$REMOTE_LISTEN" "$KH_PRIV" \
        "$IR_PUB" "0.0.0.0/0" "$(echo "$KHAREJ_HOST"):${LOCAL_LISTEN}" "$KEEPALIVE" \
        "$DO_NAT" "$EXT_IF"

      # Start local service
      systemctl enable --now "wg-quick@${IFACE}.service"
      systemctl restart "wg-quick@${IFACE}.service"
      echo "${GRN}Local WireGuard started.${NC}"

      # Show status
      wg_status_quick
      ;;
    3)
      install_deps
      IFACE="wg0"
      prompt IFACE "Interface name" "$IFACE"

      prompt KHAREJ_HOST "Remote (KHAREJ) SSH host/IP" ""
      prompt KHAREJ_USER "Remote SSH user" "root"
      prompt KHAREJ_SSH_PORT "Remote SSH port" "22"
      prompt KHAREJ_SSH_KEY "SSH private key path (for remote login)" "/root/.ssh/id_ed25519"

      prompt LOCAL_WG_IP "THIS server WG IP (for allowed on remote)" "10.66.0.1/32"
      prompt REMOTE_WG_IP "REMOTE server WG IP" "10.66.0.2/32"
      prompt REMOTE_LISTEN "REMOTE server WG ListenPort (UDP)" "51820"
      prompt KEEPALIVE "PersistentKeepalive" "25"

      gen_keys "iran-${IFACE}"
      gen_keys "kharej-${IFACE}"

      IR_PUB="$(read_key "$KEYDIR/iran-${IFACE}.pub")"
      KH_PRIV="$(read_key "$KEYDIR/kharej-${IFACE}.key")"

      yesno DO_NAT "On remote (KHAREJ), enable forwarding+NAT (MASQUERADE)?" "n"
      EXT_IF=""
      if [[ "$DO_NAT" == "yes" ]]; then
        prompt EXT_IF "Remote outbound interface (e.g. eth0)" "eth0"
      fi

      remote_bootstrap \
        "$KHAREJ_HOST" "$KHAREJ_USER" "$KHAREJ_SSH_PORT" "$KHAREJ_SSH_KEY" \
        "$IFACE" "$REMOTE_WG_IP" "$REMOTE_LISTEN" "$KH_PRIV" \
        "$IR_PUB" "$LOCAL_WG_IP" "${KHAREJ_HOST}:${REMOTE_LISTEN}" "$KEEPALIVE" \
        "$DO_NAT" "$EXT_IF"
      ;;
    4)
      wg_status_quick
      ;;
    5)
      service_manager
      ;;
    0) exit 0 ;;
    *) echo "${RED}Invalid.${NC}" ;;
  esac
done